### PR TITLE
Use a Generic Apply Changes message for bulk operations

### LINKED ISSUE #815: 複数選択してパッケージをインストールする際に Upgraded all packages と通知が出る
### Description of the bug / バグの説明

表題のとおり
1つのみ選択でも出る

### Steps to Reproduce / 再現手順

1. プロジェクトの Manage packages 画面を開く
2. 左のチェックボックスから1つ以上の未インストールパッケージを選択する
3. Install Selected を押す
4. Upgraded all packages と通知が出る

### Expected Behavior / 想定される挙動

Upgraded all packages ではなく Installed all packages 等と通知が出る

### Screenshots / スクリーンショット

_No response_

### Software Version / バージョン情報

0.1.0

### OS

Windows 11 Pro 23H2

### Additional context / 補足

_No response_

### PR DESCRIPTION
**Pull request by Spokeek**
Fixes #815

### CODE REVIEW

File: vrc-get-gui/app/projects/manage/page.tsx [hunk 1]
```diff
@@ -78,6 +78,8 @@ type RequestedOperation = {
 } | {
 	type: "remove";
 	pkgId: string;
+} | {
+	type: "appliedBulkChanges"
```
Comment (anatawa12) [inline vrc-get-gui/app/projects/manage/page.tsx:82]: the requested operation is bulk changes so the `RequestedOperation` type name should be something like `bulkChanges` I think.

File: vrc-get-gui/locales/ja.json5 [hunk 2]
```diff
@@ -76,6 +76,7 @@
     "installed {{name}} version {{version}}": "{{name}} バージョン {{version}} をインストールしました。",
     "removed {{name}}": "{{name}} をアンインストールしました。",
     "upgraded all packages": "すべてのパッケージを更新しました。",
+    "applied changes in bulk": "バルクの応用変化。",
```
Comment (anatawa12) [inline vrc-get-gui/locales/ja.json5:79]: @Sayamame-beans どうするのがいいかな

**Review by anatawa12 — APPROVED** [review]
Thank you!

File: vrc-get-gui/locales/zh_cn.json5 [hunk 3]
```diff
@@ -82,6 +82,7 @@
     "installed {{name}} version {{version}}": "已安装 {{name}} 版本 {{version}}",
     "removed {{name}}": "已删除 {{name}}",
     "upgraded all packages": "升级所有软件包",
+    "applied changes in bulk": "批量应用变化。",
```
Comment (anatawa12) [inline vrc-get-gui/locales/zh_cn.json5:85]: @lonelyicer could you check the localization?

File: vrc-get-gui/locales/ja.json5 (hunk 2 above)
Comment (Spokeek) [reply vrc-get-gui/locales/ja.json5:79]: Yeah, used DeepL as it seem that's what you used as well. I don't speak either Japanese os Chinese.

Comment (anatawa12) [reply vrc-get-gui/locales/ja.json5:79]: No problem. I think it might be better to not update languages not familiar with in feature pull requests and it might be better to update localization in another PRs. (or using something like crowdin)

Comment (Spokeek) [reply vrc-get-gui/locales/ja.json5:79]: Will do now

Comment (Sayamame-beans) [reply vrc-get-gui/locales/ja.json5:79]: 更新するのか削除するのかって完全に分かれていたと思う(同時に複数種類の操作が実行されることはなかったはず)ので、メッセージを別々に分けた方が良いような気はします…?

```suggestion
    "applied changes in bulk": "パッケージの一括変更を適用しました。",
```
とかですかね? ちょっとしっくりこないですけれど…

Comment (Sayamame-beans) [reply vrc-get-gui/locales/ja.json5:79]: en:
I think that updating, adding or deleting multiple packages in ALCOM have been completely separated operations (I don't think there were ever multiple types of operations performed at the same time), so I feel like it would be better to separate the messages...maybe?

Comment (anatawa12) [reply vrc-get-gui/locales/ja.json5:79]: > it would be better to separate the messages...maybe?

I agree

File: vrc-get-gui/app/projects/manage/page.tsx (hunk 1 above)
Comment (Spokeek) [reply vrc-get-gui/app/projects/manage/page.tsx]: used seperate types, bulkInstalled and bulkRemoved

File: vrc-get-gui/locales/zh_cn.json5 (hunk 3 above)
Comment (Spokeek) [reply vrc-get-gui/locales/zh_cn.json5]: We can do that in another PR

**Review by anatawa12 — APPROVED** [review]
LGTM! Thank you!
